---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset0
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/rakeshparkiti/app-of-apps.git
              revision: main
              files:
                - path: apps/00-app0/clusters/00-clusterlist.yaml
          - list:
              elements: []
              elementsYaml: "{{ .key.clusters | toYaml }}"
  template:
    metadata:
      name: "app0-{{.partnumber}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        chart: "{{.chart}}"
        repoURL: "{{.repoURL}}"
        targetRevision: "{{.version}}"
      destination:
        name: "{{.k8s}}"
        namespace: "{{.namespace}}"
