---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app0-master
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  labels:
    name: app0-master
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: apps/00-app0/applicationset
    repoURL: https://github.com/rakeshparkiti/app-of-apps.git
    targetRevision: main
